version: '3.8'

services:
  lmf:
    container_name: lmf
    image: lmf:latest
    # pull_policy: always
    command: "/bin/bash start.sh"
    # command: sleep 999999
    expose:
      - "4321"
    ports:
      - "9090:9090/sctp"
      - "9091:9091/udp"
      - "4321:4321"
      - "65001:65001" #exposing supl server port to make it reachable from the outside
    volumes:
      - ./envoy_proxy/envoy.yaml:/etc/envoy/envoy.yaml
    #  - ${OAI_CONF_DIR}/ue.nr.prs.fr1.106prb.conf:/LMF/prs.conf:ro
      - ${OAI_CONF_DIR}/ue.band255.3gnb.multiru.ntn-leo-RegenWithPRS.conf:/LMF/prs.conf:ro
      - ${GNB_CONF_DIR}:/LMF/gnb_confs:ro
    restart: on-failure
    networks:
      privnet:
        aliases:
          - lmf_net.org
        ipv4_address: 192.168.70.140

networks:
  privnet:
    external: true
   # name: free5gc-compose_privnet
    name: oai-cn5g-public-net
